import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import HeaderComponent from "../components/atoms/header/header";
import TabClientWrapper from "../components/organisms/tabs/TabClientWrapper";
import "./globals.css";
import "./layout.scss";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
      </head>
      <body className="min-h-screen flex flex-col bg-white">
        <div>
          <HeaderComponent />
        </div>
        <main className="flex-1 overflow-y-auto pt-16 pb-20">
          {children}
        </main>
        <footer className="fixed bottom-0 left-0 right-0">
          <TabClientWrapper />
        </footer>
      </body>
    </html>
  );
}
